### ISSUE TITLE
.NET CsCheck PBT library

### ISSUE THREAD

**Issue by AlgorithmsAreCool** [stevana/stateful-pbt-with-fakes#2]
There is a newer and perhaps more featureful PBT library called CsCheck. If I understand correctly, it supports both the parallel and stateful testing features you describe.

https://github.com/AnthonyLloyd/CsCheck

See:
- https://github.com/AnthonyLloyd/CsCheck?tab=readme-ov-file#model-based-testing 
- https://github.com/AnthonyLloyd/CsCheck?tab=readme-ov-file#concurrency-testing

**Comment by stevana** [comment]
I've added it to the list, thanks!
